version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: playlisted_db
    restart: always
    environment:
      POSTGRES_USER: gamemaster
      POSTGRES_PASSWORD: playlisted123
      POSTGRES_DB: playlisted_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: